[tools]
"aqua:github/copilot-cli" = "latest"
"aqua:joshmedeski/sesh" = "latest"
bun = "latest"
"go:github.com/joshmedeski/sesh" = "latest"
node = "lts"
opencode = "latest"
pi = "latest"
topgrade = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
zig = "master"
