[tools]
"aqua:joshmedeski/sesh" = "latest"
node = "lts"
opencode = "latest"
television = "latest"
topgrade = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
zoxide = "latest"
starship = "latest"
bob = "latest"
eza = "latest"
gh = "latest"
uv = "latest"
