#!/bin/bash

# Define the icons and labels
lock="🔒 Lock"
suspend="💤 Suspend"
reboot="🔄 Reboot"
shutdown="⏻ Shutdown"
logout="🚪 Logout"

# Show the menu using Fuzzel
selected=$(echo -e "$lock\n$suspend\n$reboot\n$shutdown\n$logout" | rofi -dmenu -p "Power" -theme-str 'window {width: 20%;} listview {lines: 5;}')

case $selected in
    "$lock")
        swaylock -f --screenshots --clock --indicator --effect-scale 0.5 --effect-blur 7x5 --effect-scale 2
        ;;
    "$suspend")
        systemctl suspend
        ;;
    "$reboot")
        systemctl reboot
        ;;
    "$shutdown")
        systemctl poweroff
        ;;
    "$logout")
        niri msg action quit
        ;;
esac
