### Variables

# Mod Modifier (Super Key)
set $mod Mod4

# Vim Directional Keys
set $left h
set $down j
set $up k
set $right l

# Preferred Applications
set $term ghostty
set $browser helium
set $menu rofi -show combi -no-persist-history
set $wallpaper /home/alaeddine/Pictures/Wallpapers/ashya-jamila.jpg

# Global UI Theme Colors
set $bg-color            #000000
set $inactive-bg-color   #222222
set $text-color          #eeeeee
set $inactive-text-color #888888
set $urgent-bg-color     #8c001a
set $border-color        #000000

# Window Styling Rules
client.focused          $border-color    $bg-color            $text-color          $border-color     $border-color
client.focused_inactive $inactive-bg-color $inactive-bg-color $inactive-text-color $inactive-bg-color $inactive-bg-color
client.unfocused        $inactive-bg-color $inactive-bg-color $inactive-text-color $inactive-bg-color $inactive-bg-color
client.urgent           $urgent-bg-color $urgent-bg-color     $text-color          $urgent-bg-color $urgent-bg-color

# Global Font Engine
font pango:JetBrainsMono Nerd Font Mono 10
