### Output

# Wallpaper Setup
output * bg $wallpaper fill

# Asahi Mac Resolution/Scale
output eDP-1 {
    resolution 2560x1600
    scale 2
    pos 0 0
    subpixel none
    scale_filter smart
    adaptive_sync on
}
