## Rules

# Default Layout Model
workspace_layout tabbed
default_border pixel 0

# Floating TUI App Specifications
for_window [app_id="foot" title="Bluetooth TUI"] floating enable, resize set 800 600
for_window [app_id="foot" title="Wifi TUI"] floating enable, resize set 800 600
for_window [app_id="foot" title="Task Manager"] floating enable, resize set 1500 800
for_window [app_id="foot" title="Sound TUI"] floating enable, resize set 800 600
for_window [title="^Picture-in-Picture$"] floating enable, sticky enable


