### Daemons

# Background Sync & System State Frameworks
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store
exec wl-clip-persist --clipboard regular
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec mako
exec swayrd
exec wayland-pipewire-idle-inhibit
exec batsignal -w 25 -c 10 -d 2

# Hardware Power State Watcher
exec swayidle -w \
    timeout 300 'swaylock -f --screenshots --clock --indicator --effect-scale 0.5 --effect-blur 7x5 --effect-scale 2' \
    timeout 600 'swaymsg "output * power off"' \
    resume 'swaymsg "output * power on"' \
    timeout 900 'systemctl suspend' \
    before-sleep 'swaylock -f --screenshots --clock --indicator --effect-scale 0.5 --effect-blur 7x5 --effect-scale 2'
