### Daemons



# Background Sync & System State Frameworks
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store
exec wl-clip-persist --clipboard regular
exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP XDG_CURRENT_DESKTOP QT_COLOR_SCHEME QT_QPA_PLATFORMTHEME
exec hash dbus-update-activation-environment 2>/dev/null && dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP XDG_CURRENT_DESKTOP=sway
exec /usr/libexec/hyprpolkitagent
exec mako
exec swayrd
exec wayland-pipewire-idle-inhibit
exec batsignal -w 25 -c 10 -d 2

# Hardware Power State Watcher
exec swayidle -w \
    timeout 600 'pidof hyprlock || hyprlock' \
    timeout 1200 'swaymsg "output * power off"' \
    resume 'swaymsg "output * power on"' \
    timeout 1800 'systemctl suspend' \
    before-sleep 'pidof hyprlock || hyprlock'
