### Bar

# Bar Architecture Block
bar {
    id bar-0
    position bottom
    font pango:JetBrainsMono Nerd Font Propo 8.5
    status_command ~/.config/sway/status.sh

    colors {
        background $bg-color
        separator  $border-color
        statusline $text-color

        focused_workspace   $border-color    $border-color    $text-color
        active_workspace    $inactive-bg-color $inactive-bg-color $text-color
        inactive_workspace  $bg-color        $bg-color        $inactive-text-color
        urgent_workspace    $urgent-bg-color $urgent-bg-color $text-color
    }
}
